plugins {
    alias(libs.plugins.android.application)
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { localProperties.load(it) }
}
def groqApiKey = localProperties.getProperty("GROQ_API_KEY", "")

android {
    namespace 'com.example.aimentor'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.aimentor"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "GROQ_API_KEY", "\"${groqApiKey}\""
        buildConfigField "String", "GROQ_BASE_URL", "\"https://api.groq.com/\""
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.recyclerview
    implementation libs.cardview
    implementation libs.viewpager2
    implementation libs.swiperefreshlayout
    implementation libs.room.runtime
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.okhttp
    implementation libs.okhttp.dnsoverhttps
    implementation libs.gson
    implementation libs.mlkit.text.recognition
    annotationProcessor libs.room.compiler
    testImplementation libs.junit
    testImplementation libs.mockwebserver
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
